apiVersion: batch/v1
kind: Job
metadata:
  name:  my-opslevel-report-deploy-generic
  generateName: app-opslevel-report-deploy-generic
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: opslevel-report-deploy-generic
    containers:
    - name: slack-notification
      image: curlimages/curl
      command:
      - "curl"
      - "-X"
      - "POST"
      - "--data-urlencode"
      - "payload={\"service\": \"jbtest\",\"deployer\": {\"email\": \"automation@opslevel.com\"},\"deployed_at\": \"14:00\",\"description\": \"Deployed by CI Pipeline: Deploy #235\"}"
      - "${OPSLEVEL_GENERIC_URL}"
      env:
        - name: OPSLEVEL_GENERIC_URL
          valueFrom:
            secretKeyRef:
              name: ops-level-generic
              key: url
    restartPolicy: Never
  backoffLimit: 1
